# Generated by Django 4.2.4 on 2023-09-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_quote_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='born_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
